version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
  - dependency-name: eslint
    versions:
    - 7.19.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
